### ISSUE TITLE
how do you install your framework

### ISSUE THREAD

**Issue by justageek** [bayareawebpro/basher-framework#5]
I don't quite understand how to install the framework, I'm a oh-my-zsh user.

**Comment by bayareawebpro** [comment]
Find the **plugins** directory in your zsh installation.

Add the following to the new shell file with any name.   I like to keep the framework in my home directory, but you can put it wherever, just make sure the BASHER_PATH variable points to it. What will happen is all the framework's functions will be sourced into your console session which makes all the commands available.   

```
#!/usr/bin/env bash

# Declare Basher Framework Path
export BASHER_PATH="$HOME/basher-framework"

# shellcheck source=$BASHER_PATH/app.sh
source "$BASHER_PATH/app.sh"
```

Copy the ENV file and remove the .default extension.  That fill should like within the framework directory.

https://github.com/bayareawebpro/basher-framework/blob/master/.env.default
